#.travis.yml
language: node_js
node_js:
  - "8.9"
addons:
  ssh_known_hosts: funlab.fr
  apt:
    packages:
    - sshpass
branches:
  only:
    - dev

script:
  - npm install --production

after_success:
  - sshpass -p ${SSH_PASSWORD} ssh -v o SSH_USER=HOST_IP ${SSH_USER}@funlab.fr 'find api.funlab.fr/ ! -path "*./public*" | xargs rm -rfd'
  - sshpass -p ${SSH_PASSWORD} scp -v -r ${TRAVIS_BUILD_DIR}/* ${SSH_USER}@funlab.fr:${DOMAIN_DIRECTORY}/

notifications:
  email:
    on_failure: change
    on_success: change
