#.travis.yml
language: generic
node_js:
  - "8.9"
addons:
  ssh_known_hosts: funlab.fr
  apt:
    packages:
    - sshpass
branches:
  only:
    - master

after_success:
  - sshpass -p ${SSH_PASSWORD} ssh -v ${SSH_USER}@funlab.fr 'find prod.funlab.fr/ ! -path "*/.credentials*" -path "*/public*" | xargs rm -rfd'
  - sshpass -p ${SSH_PASSWORD} scp -v -r ${TRAVIS_BUILD_DIR}/* ${SSH_USER}@funlab.fr:prod.funlab.fr/
  - sshpass -p ${SSH_PASSWORD} ssh -v ${SSH_USER}@funlab.fr 'cd prod.funlab.fr/ && npm install --production'

notifications:
  email:
    on_failure: change
    on_success: change
