#.travis.yml
language: node_js
node_js:
  - "8.9"
addons:
  ssh_known_hosts: funlab.fr
  apt:
    packages:
    - sshpass
branches:
  only:
    - dev

# script:
#   - npm install --production

after_success:
  - sshpass -p ${SSH_PASSWORD} ssh -v ${SSH_USER}@funlab.fr 'find funlab.fr/ ! -path "*./public*" | xargs rm -rfd'
  - sshpass -p ${SSH_PASSWORD} scp -v -r ${TRAVIS_BUILD_DIR}/* ${SSH_USER}@funlab.fr:funlab.fr/
  - sshpass -p ${SSH_PASSWORD} ssh -v ${SSH_USER}@funlab.fr 'cd funlab.fr/ && npm install --production'

notifications:
  email:
    on_failure: change
    on_success: change
